/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}/formFour` | `/formFour`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}/formThree` | `/formThree`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}/formTwo` | `/formTwo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(child)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}/formFour` | `/formFour`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}/formThree` | `/formThree`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}/formTwo` | `/formTwo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(child)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(child)'}${'/(addForm)'}/formFour${`?${string}` | `#${string}` | ''}` | `/formFour${`?${string}` | `#${string}` | ''}` | `${'/(child)'}${'/(addForm)'}/formThree${`?${string}` | `#${string}` | ''}` | `/formThree${`?${string}` | `#${string}` | ''}` | `${'/(child)'}${'/(addForm)'}/formTwo${`?${string}` | `#${string}` | ''}` | `/formTwo${`?${string}` | `#${string}` | ''}` | `${'/(child)'}${'/(addForm)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}/formFour` | `/formFour`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}/formThree` | `/formThree`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}/formTwo` | `/formTwo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(child)'}${'/(addForm)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
